### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by EugenMayer** [jon5477/consul-api#1]
thank you for taking up the work to continue. I asked for an answer about the project status of 'Ecwid/consul-api' inhttps://github.com/Ecwid/consul-api/issues/249

Are you going to maintain the consul-api a little further - are you interested in others helping so a possible successor could be created?

**Comment by jon5477** [comment]
No problem. I saw the original repository has not addressed a lot of issues and since I use this in production these issues need to be resolved. I welcome contributors if they are interested in helping to maintain this project.

**Comment by EugenMayer** [comment]
Well to similar reasons, i'am interested in keeping the package maintained. I do not have big "feature" goals at all. More or less my goal would be

1. keep the libraries production ready (CVEs, deprecations), good example is the removal of httpclient4 (which you alread did)
2. Ensure we stay with the non-deprecated APIs of consul (which you already did, 1.18)
3. Keep the exposed SDK/Interface sane 

The list is ordered in the way i would put time into the project. So if those goals can be aligned with your ideas, i would be happy to jump on the ship.

I created some PRs to ensure we run tests every commit PR (to avoid what happened just now, the test did not run anymore since you introduced filter), and fixed the filter.
