### ISSUE TITLE
Consider publishing it under a new namespace

### ISSUE THREAD

**Issue by EugenMayer** [jon5477/consul-api#4]
Since it is not expected to see any movement by https://github.com/Ecwid/consul-api i would  suggest publish the package under a different namespace / package onto nexus.

We will need to 

- add package signing
- add gh release task

**Comment by jon5477** [comment]
I would not mind publishing it to GitHub packages. Is there a specific use case you have that would require the package to be published on nexus?

**Comment by EugenMayer** [comment]
Well i need it published, but i have my own nexus and can and did publish it on it anyway already. So it is lesser for me, it's for others to consume the artifact the usual way.

Publishing it to github packages would need the person to add an additional repository to the most probably already existing maven nexus one. I'am fine with that.

The last time i looked at github packages for maven repos, it looked cumbersome. Maybe you teach me something else :)

**Comment by jon5477** [comment]
I've added the GitHub Actions to the repository and published the Maven artifact to GitHub packages. I've also updated the Wiki page on how to pull the artifact for anyone who wishes to use it. I'm currently in the process of refactoring a major portion of the codebase to clean up some Consul API deprecations and issues too.

I've adjusted the GitHub Actions to not run on every single push workflow as I expect testing to happen more frequently when doing development locally, I think the workflow is best to run when PRs are opened and pushes are made to open PRs.

**Comment by EugenMayer** [comment]
I assume you are simply not interested in any contributions, since you simply ignore them

**Comment by jon5477** [comment]
I wouldn't say that, I saw your PR and made changes as needed to the master branch on the repository. I personally don't know how to push dependencies to Nexus because I have never tried so this is a task I'll need to prepare for in the future. If you wish you can help on that particular workflow, you are also welcome to help with the refactoring on the library. I am not sure why you rush to the conclusion that I am ignoring your contributions
